### ISSUE TITLE
MIMIC-CXR Pretrain Dataset Pre-Processing

### ISSUE THREAD

**Issue by SinuoWang** [kakaobrain/cxr-clip#1]
Thank you for releasing the code of this fantastic work!  :)

I have a few questions regarding the data preprocessing of MIMIC dataset. I saw there are 5 steps in the preprocessing in the ReadME, I am wondering whether there is any code to perform any data cleaning. Because there are some samples that miss the 'findings' or 'impression' and after the back translation, this will give weird augmented text as shown in my screenshot. 

From what I know the only preprocessing code is the "back_translation.py", did I miss any preprocessing code? And if there are other pre-processing steps, could you release these code? 

Cheers!

![mimic](https://github.com/kakaobrain/cxr-clip/assets/76032182/704be5dd-8d83-4ed2-91ea-0d30ed4e3343)
![图片_20240126223337](https://github.com/kakaobrain/cxr-clip/assets/76032182/7b294a38-5e77-41af-b1dd-1444b123316a)

**Comment by kihyunU** [comment]
If any study missing "findings", the text column should be [impression]. Sorry for insufficient description.

**Comment by SinuoWang** [comment]
> If any study is missing "findings", the text column should be [impression]. Sorry for insufficient description.

Thank you for your clarifications! I am also curious whether other text cleaning steps are required, such as removing the "\n" in the text, etc. I know this is kinda trivial, but I just wanna double check.

Thanks in advance :)

**Comment by kihyunU** [comment]
Yes we removed "\n". uppercase letter and lowercase letter don't matter because it will be processed by tokenizer.

**Comment by GravitySaika** [comment]
Hi! I'm wondering how long does it takes in the augmentation stage, I used 1 A40 GPU to handle it, but is shows that it needs 13h to finish. Is that normal?
![image](https://github.com/kakaobrain/cxr-clip/assets/48847883/9f5fb6e1-fe02-4019-af54-e9f3677cf242)

**Comment by kihyunU** [comment]
I think it is normal. This process includes sequential two models with beam search. So it will take some time.

**Comment by Orange2107** [comment]
Hi @kihyunU 
It is a meaningful work.
I would like to ask:
The "text" in each subject is like: [[Findings1,Impression1],[Findings2,Impression2][Findings3,Impression3]...[Findings,Impression]].
Is this correct?
Thank you
