### ISSUE TITLE
The checkpoints provided does not give expected result

### ISSUE THREAD

**Issue by ChocoOreal** [kakaobrain/cxr-clip#10]
I tried to evaluate I2T retrieval with the official weight but the results are still not comparable to the figures in your paper. I used the resnet50 trained on MIMIC and Chexpert. Here is the results I got:

![image](https://github.com/kakaobrain/cxr-clip/assets/83420027/1798de31-a816-46be-8f9f-aebfd22a867c)

Can you share what I should notice when inference to produce the figures in your paper?

**Comment by kihyunU** [comment]
what is the dataset you used? Please check [datasets](https://github.com/kakaobrain/cxr-clip/tree/main/datasets) for processing.

**Comment by ChocoOreal** [comment]
> what is the dataset you used? Please check [datasets](https://github.com/kakaobrain/cxr-clip/tree/main/datasets) for processing.

I used MIMIC-CXR test split for evaluation. I preprocess it into the csv file as described in [image-text evaluation](https://github.com/kakaobrain/cxr-clip/tree/main/datasets#image-text-evaluation-dataset)

**Comment by phphuc612** [comment]
I have experimented the retrieval with `max` function is choosing the longest text. The result is comparable with acceptable error.
This is a solid work.

**Comment by kihyunU** [comment]
As @phphuc612, we extracted the longest text between "finding" and "impression". Sorry for confusion.
