### ISSUE TITLE
About few-shot evaluation

### ISSUE THREAD

**Issue by phphuc612** [kakaobrain/cxr-clip#11]
Thank you for your great work!

I want to ask about few-shot noted in your paper, what does 10% or 100% really mean in few-shot(10%) and few-shot(100%)? 
If possible, can you link the few-shot evaluation code for me please?
I deeply appreciate your help.

**Comment by kihyunU** [comment]
The 10% means using 10% of training set (few-shot) and 100% means using 100% of training set (full-shot)

the code is in README
`
python finetune.py --config-name finetune_10 hydra.run.dir=${SAVE_DIR} data_train=rsna_pneumonia data_valid=rsna_pneumonia model.load_backbone_weights=${CKPT_PATH/model-best.tar} # 10%
python finetune.py hydra.run.dir=${SAVE_DIR} data_train=rsna_pneumonia data_valid=rsna_pneumonia model.load_backbone_weights=${CKPT_PATH/model-best.tar} # 100%
`
