### ISSUE TITLE
Some confusion about pre training datasets

### ISSUE THREAD

**Issue by GravitySaika** [kakaobrain/cxr-clip#3]
Thanks a lot for the releasing code!

I have some doubts about the use of pre training datasets

In /cxr-clip/cxrclip/data/datasets/imagetext.py

![image](https://github.com/kakaobrain/cxr-clip/assets/48847883/9cc3875d-793f-4436-a93b-ed1b9cac0715)

This code doesn't seem quite correct. After so many if statements, it seems that the selection of images in this code does not meet the requirements of "sample images from two distinct views as possible" described in the paper, and some parts may even appear incorrect. Because every time the 80th command is executed, the "image_path_list" variable is reset instead of truly becoming a list for storing image paths.

This also raises another question for me, how are the elements of the list in the view column counted for the training csv of MIMIC-CXR? For example, in a study, I have two AP images, one PA image, and two Lateral images. Should my list be [AP, AP, PA, Lateral, Lateral] or just [AP, PA, Lateral]?

Looking forward to your answer!

**Comment by kihyunU** [comment]
If you want to sample distinct views. The csv column should have each view columns like screenshoot. Details are in [Dataset page](https://github.com/kakaobrain/cxr-clip/tree/main/datasets). 
So I a study has two AP images, one PA image, and two Lateral images. The AP column is [path of AP1, path of AP2], the PA column is [path of PA], and the Lateral column is [path of Lateral1, path of Lateral2]
<img width="1070" alt="스크린샷 2024-03-25 오후 12 40 01" src="https://github.com/kakaobrain/cxr-clip/assets/20676906/f350a24a-a816-4420-9ad8-a1ee0acdeccf">
