### ISSUE TITLE
[BOS] and [EOS] token missing

### ISSUE THREAD

**Issue by jiajinuiuc** [kakaobrain/cxr-clip#5]
Hello,

thanks for sharing the code!

I met two problems when using the code:

(1) when I try to initialize the tokenizer, there is a line `tokenizer.bos_token_id = tokenizer.cls_token_id`

I receive an error: `TypeError: 'int' object is not iterable`

My understanding is that, since you donot define the **[BOS]** token (because you are using a BERT tokenizer), you cannot directly define a value of this token. 

(2) following the first question, I found the global text feature extraction of the text encoder uses the **[EOS]** token. But this token does not exist in the BERT tokenizer either.

Could you please let me know how to correctly initialize your tokenizer with both **[BOS]** and **[EOS]** tokens and their corresponding ids?

Thank you!

**Comment by kihyunU** [comment]
(1) I recommed you to check huggingface version. ours: `huggingface-hub==0.16.4`.
(2) The ClinicalBert is based on BertTokenizer, which used [SEP] token as [EOS]

#leverage checkpoints for Bert2Bert model… # use BERT’s cls token as BOS token and sep token as EOS token encoder
(from [https://huggingface.co/transformers/v3.3.1/model_doc/bertgeneration.html](https://huggingface.co/transformers/v3.3.1/model_doc/bertgeneration.html))
